export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_PHOTO = 'FETCH_USER_PHOTO';
export const FETCH_PHOTO_BY_ID = 'FETCH_PHOTO_BY_ID';
export const LIKE_USER_PHOTO = 'LIKE_USER_PHOTO';
export const UNLIKE_USER_PHOTO = 'UNLIKE_USER_PHOTO';
export const FETCH_USER_FOLLOWER = 'FETCH_USER_FOLLOWER';
export const FETCH_USER_FOLLOWING = 'FETCH_USER_FOLLOWING';
export const FOLLOW_USER = 'FOLLOW_USER';
export const UNFOLLOW_USER = 'UNFOLLOW_USER';

export const UPDATE_TIMELINE_PAGE = 'UPDATE_TIMELINE_PAGE';
export const UPDATE_USER_PHOTO_PAGE = 'UPDATE_USER_PHOTO_PAGE';
export const UPDATE_PHOTO_COMMENT_PAGE = 'UPDATE_PHOTO_COMMENT_PAGE';
export const UPDATE_USER_FOLLOWING_PAGE = 'UPDATE_USER_FOLLOWING_PAGE';
export const UPDATE_USER_FOLLOWER_PAGE = 'UPDATE_USER_FOLLOWER_PAGE';

export const FETCH_TIMELINE = 'FETCH_TIMELINE';

export const RESET_ENTITIES = 'RESET_ENTITIES';
export const RESET_PAGINATION = 'RESET_PAGINATION';
export const RESET_TIMELINE = 'RESET_TIMELINE';
export const RESET_TIMELINE_PAGE = 'RESET_TIMELINE_PAGE';
export const RESET = 'RESET';
