export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_PHOTO = 'FETCH_USER_PHOTO';
export const LIKE_USER_PHOTO = 'LIKE_USER_PHOTO';
export const UNLIKE_USER_PHOTO = 'UNLIKE_USER_PHOTO';
export const FETCH_USER_FOLLOWER = 'FETCH_USER_FOLLOWER';
export const FETCH_USER_FOLLOWING = 'FETCH_USER_FOLLOWING';
export const FOLLOW_USER = 'FOLLOW_USER';
export const UNFOLLOW_USER = 'UNFOLLOW_USER';
export const RESET_USER = 'RESET_USER';

export const FETCH_TIMELINE = 'FETCH_TIMELINE';
export const RESET_TIMELINE = 'RESET_TIMELINE';

export const RESET = 'RESET';
